### PR TITLE
Support Rectangle and Patch graphical objects

### PR DESCRIPTION
**Pull request by kubark42**
Add support for plotting log10 of Rectangle and Patch objects as well. 

Required a little bit of abstraction in order to keep the code readable. I hope this is an improvement.

Tested and works as expected.

#### Test code
```
close all
clear

% Nice straight line
x = -1e6:1e6;

% Simple plot of original data
subplot(3,1,1)
plot(x);

% Plot of original data and rectangle
subplot(3,1,2)
h = plot(x);

% Draw rectangle only on top half of plane
rect_height = round(max(h.Parent.YTick));
rectangle('Position', [1, 0, length(h.XData)-1, rect_height],'FaceColor',[1,0.,0., .1])

% Log plot of data and rectangle
subplot(3,1,3)
h = plot(x);

% Draw rectangle only on top half of plane
rect_height = round(max(h.Parent.YTick));
rectangle('Position', [1, 0, length(h.XData)-1, rect_height],'FaceColor',[1,0.,0., .1])
symlog('y')
```

#### Results
screen shot 2016-12-28 at 2 27 56 pm

### CODE REVIEW

**Comment by kubark42** [comment]
Actually, hang on, found a tiny bug that I introduced when pulling this code out of a larger changeset.

**Comment by kubark42** [comment]
Nevermind, it was just some variables in my workspace that needed clearing.

**Comment by raaperrotta** [comment]
This looks good! How do you imagine this being used? I sometimes highlight regions of the plot with a patch object and those are typically vertical or horizontal boundaries, but any lines that aren't vertical or horizontal in linear space would not be straight in (sym)log space if we mapped the whole edge and not just the corners. I think it is still useful even if the conversion isn't perfect so I suggest we include it anyway but note the behavior clearly in the help text.

Also, you mentioned you are developing in R2016a. Have you tested this in other versions, too? I have been trying to maintain compatibility with versions 2014b and on.

**Comment by kubark42** [comment]
I was using it to show an exclusion zone for some scatterpoint data. Anything that was in the top half was considered to be bad results.

Good point about patches, I hadn't considered that. Simple Rectangles will not have this problem. Patches could be resolved by interpolating along the line. I imagine that 20 points along each section would be good enough.

What kind of help text were you thinking?

> Also, you mentioned you are developing in R2016a. Have you tested this in other versions, too?

I haven't tested on other than 2016a. Do you know how we could test it on 2014b?

**Comment by raaperrotta** [comment]
Patches in log space have straight lines in MATLAB 2016b.

```matlab
set(gca(),'XScale','log')
patch([1,1,0,0]*10+1,[1,0,0,2],[0.8,0.2,0.2],'EdgeColor','None')
```
logpatch

So I think that is the proper behavior for symlog, too.

I have MATLAB 2014b - 2016b installed and will test these changes in each. I keep some basic unit test functions [here](https://github.com/raaperrotta/tests).

**Comment by raaperrotta** [comment]
These changes work in all versions 2014b to 2016b. I have merged them into master. Thank you!

**Comment by kubark42** [comment]
Thanks for testing it!

**Pull request merged**
