### PR TITLE
Display: Skip ticks in order to reduce clutter

### PR DESCRIPTION
**Pull request by kubark42**
Inspired by Matlab's `semilogy()` behavior, this aims at having a maximum of 5 or 6 tick marks, and when there are too many  increases the step size to try to balance around 3 to 6 tick marks.

Note that this only happens if the user hasn't set `C`.

#### Example
```
close all
clear

% Normal behavior unchanged
a0 = subplot(3,2,1);
x = 1:1e3;
plot(x);
symlog(a0, 'y')

% `eps` is the tiniest number Matlab knows how to make, so this plot has enormous dynamic range
a1 = subplot(3,2,2);
x = eps:1e6;
plot(x);
symlog(a1, 'y')

% Zero crossing
a2 = subplot(3,2,3);
x = -1e3:1e3;
plot(x);
symlog(a2, 'y')

% Zero crossing with large dynamic range
a3 = subplot(3,2,4);
x = -1e15:1e10:1e15;
plot(x);
symlog(a3, 'y')

% Negative plots still work correctly
a4 = subplot(3,2,5);
x = -1e4:-1;
plot(x);
symlog(a4, 'y')

% Plot which barely crosses 0.
a5 = subplot(3,2,6);
x = -1e7:1;
plot(x);
symlog(a5, 'y')
```

#### Result
screen shot 2016-12-28 at 3 29 40 pm

### CODE REVIEW

**Comment by kubark42** [comment]
@raaperrotta, I'm crossing my fingers that this will work on 2014b. It relies on simple math functions and plotting functionality which is already in symlog.

**Comment by raaperrotta** [comment]
I am creating a branch (same as before) so I can test it before merging it with the master.

**Comment by kubark42** [comment]
Cool, thanks! Let me know if you pick up on any bugs or glitches. My tested scenarios can't possibly cover all the myriad things Matlab can throw at it.

**Comment by raaperrotta** [comment]
When you call symlog w/o arguments, it executes on x, y, and z. In the past, this has worked fine even with 2D axes, but your bounds checking in find_minmax_value isn't set up to handle empty data sets. How about using the axes limits set by MATLAB? In place of your call to `find_minmax_value`:

```matlab
a = get(ax,[var,'Lim']); % MATLAB's automatically-chosen limits
b = a(2);
a = a(1);
```

Also, in the case where a>0 we could just use built-in log-scaling. And for b<0 we may be able to do something similar without involving C.

**Comment by kubark42** [comment]
> How about using the axes limits set by MATLAB? In place of your call to find_minmax_value

Let me look into this. I think your instinct is right that it could work. Would you like another PR opened up, targetting `manage-tick-resolution`?

> Also, in the case where a>0 we could just use built-in log-scaling. 

Yes, we could totally do this. Is it more valuable to you to have a consistent look and feel or to have a simpler algorithm? I see good arguments for both, and am happy to make this work either way.

> And for b<0 we may be able to do something similar without involving C.

Hmm... Have to trick Matlab into plotting `semilog...` upside down?

**Comment by raaperrotta** [comment]
Yeah a new PR for the working branch sounds great. I will be away from my computer for a few days so I won't have a chance to test and merge. I encourage you to run the tests in tests/symlogTest.m while you develop and to add to them (the tests).

**Comment by kubark42** [comment]
@raaperrotta, good suggestion on finding the limits with `get(ax,[var,'Lim']);`. I ran into an edge case where if `Inf` is in the dataset Matlab won't plot it, but it will drive the `min()` to -Inf. Switching to getting the axis limits solved the problem neatly.

**Pull request merged**
